spring.application.name=rh
# Configurações do Banco de Dados
spring.jpa.database=postgresql
spring.sql.init.platform=postgres
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/rh_db
spring.datasource.username=postgres
spring.datasource.password=postgres